<Project>
  <Import Project="..\..\..\..\Directory.Build.props" />

  <PropertyGroup>
    <BaseIntermediateOutputPath>obj-custom\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
